oenik_prog3_2020_2_rcn5hx/Computers.Web/Models/Processor.cs
// <copyright file="Processor.cs" company="RCN5HX">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
namespace Computers.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    // Form Model / MVC ViewModel egyaránt lesz

    /// <summary>
    /// A WebModel version of a processor.
    /// </summary>
    public class Processor
    {
        /// <summary>
        /// Gets or Sets the id of a processor.
        /// </summary>
        [Display(Name = "Processor Id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets the socket of a processor.
        /// </summary>
        [Display(Name = "Processor Socket Name")]
        [Required]
        public string Socket { get; set; }

        /// <summary>
        /// Gets or Sets the name of a processor.
        /// </summary>
        [Display(Name = "Processor Model Name")]
        [Required]
        [StringLength(30, MinimumLength = 6)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets the Name of a company which produced the processor.
        /// </summary>
        [Display(Name = "Processor Company Name")]
        [Required]
        [StringLength(30, MinimumLength = 3)]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets the price of a processor.
        /// </summary>
        [Display(Name = "Processor Price")]
        [Required]
        public int Price { get; set; }

        /// <summary>
        /// Gets or Sets the ghz of a processor.
        /// </summary>
        [Display(Name = "Processor Ghz")]
        [Required]
        public double Ghz { get; set; }

        /// <summary>
        /// Gets or Sets the core count of a processor.
        /// </summary>
        [Display(Name = "Processor Core Count")]
        [Required]
        public int CoreCount { get; set; }

        /// <summary>
        /// Gets or Sets a value indicating whether the processor is damaged or not.
        /// </summary>
        [Display(Name = "Processor Damage")]
        [Required]
        public bool Damaged { get; set; }
    }
}

oenik_prog3_2020_2_rcn5hx/Computers.Web/Controllers/ProcessorsController.cs
// <copyright file="ProcessorsController.cs" company="RCN5HX">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
namespace Computers.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using Computers.Logic;
    using Computers.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// Controls the web requests, and posts.
    /// </summary>
    public class ProcessorsController : Controller
    {
        private IManufactureLogic logic;
        private IMapper mapper;
        private ProcessorListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessorsController"/> class.
        /// </summary>
        /// <param name="logic">instance of an IManufactureLogic.</param>
        /// <param name="mapper">instance of an IMapper.</param>
        public ProcessorsController(IManufactureLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new ProcessorListViewModel();
            this.vm.EditedProcessor = new Models.Processor();

            var processors = this.logic.GetAllProcessor();
            this.vm.ListOfProcessor = this.mapper.Map<IList<Data.Processor>, List<Models.Processor>>(processors);
        }

        /// <summary>
        /// Creates the Index page of the Processors.
        /// </summary>
        /// <returns>an IActionResult, which creates a view.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("ProcessorsIndex", this.vm);
        }

        /// <summary>
        /// Gets the Details page.
        /// </summary>
        /// <param name="id">The id of a selected processor.</param>
        /// <returns>a details page of the given processor.</returns>
        public IActionResult Details(int id)
        {
            return this.View("ProcessorsDetails", this.GetProcessorModel(id));
        }

        /// <summary>
        /// Removes a processor of the given ID.
        /// </summary>
        /// <param name="id">the selected processor's id.</param>
        /// <returns>back to the Index page, with a new TempData.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete FAIL";
            if (this.logic.RemoveProcessor(this.logic.GetOneProcessor(id)))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Gets an edit page, of the processor.
        /// </summary>
        /// <param name="id">the selected processor's id.</param>
        /// <returns>the index page of the processors..</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedProcessor = this.GetProcessorModel(id);
            return this.View("ProcessorsIndex", this.vm);
        }

        /// <summary>
        ///  Decides, if you want to add a new processor, or change an existing one, if you can change it, changes it.
        /// </summary>
        /// <param name="proc">an instance of a processor.</param>
        /// <param name="editAction">this string decides if you want to add, or change.</param>
        /// <returns>Returns back to the Index page, with a new TempData.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Processor proc, string editAction)
        {
            if (this.ModelState.IsValid && proc != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        this.logic.AddProcessor(proc.Name, proc.Socket, proc.Price, proc.Ghz, proc.CoreCount, proc.Damaged, proc.CompanyName == "AMD" ? 1 : 2);
                    }
                    catch (ArgumentException e)
                    {
                        this.TempData["editResult"] = "AddProc FAIL: " + e.Message;
                    }
                }
                else
                {
                    if (!this.logic.ChangeProcessor(proc.Id, proc.Socket, proc.Damaged, proc.Ghz, proc.CoreCount, proc.Name, proc.CompanyName == "AMD" ? 1 : 2, proc.Price))
                    {
                        this.TempData["editResult"] = "Edit FAIL";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.TempData["editAction"] = "Edit";
                this.vm.EditedProcessor = proc;
                return this.View("ProcessorsIndex", this.vm);
            }
        }

        private Models.Processor GetProcessorModel(int id)
        {
            Data.Processor oneProc = this.logic.GetOneProcessor(id);
            return this.mapper.Map<Data.Processor, Models.Processor>(oneProc);
        }
    }
}

oenik_prog3_2020_2_rcn5hx/Computers.Web/Views/Processors/ProcessorsDetails.cshtml
@model Computers.Web.Models.Processor

@{
    ViewData["Title"] = "ProcessorsDetails";
}

<h2>Datasheet of one processor</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
        <tr>
            <td>@Html.DisplayNameFor(m => m.Id)</td>
            <td>@Html.DisplayFor(m => m.Id)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.CompanyName)</td>
            <td>@Html.DisplayFor(m => m.CompanyName)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.Name)</td>
            <td>@Html.DisplayFor(m => m.Name)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.CoreCount)</td>
            <td>@Html.DisplayFor(m => m.CoreCount)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.Ghz)</td>
            <td>@Html.DisplayFor(m => m.Ghz)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.Price)</td>
            <td>@Html.DisplayFor(m => m.Price)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.Socket)</td>
            <td>@Html.DisplayFor(m => m.Socket)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.Damaged)</td>
            <td>@Html.DisplayFor(m => m.Damaged)</td>
        </tr>
</table>

oenik_prog3_2020_2_rcn5hx/Computers.Web/Views/Processors/ProcessorsEdit.cshtml
@model Computers.Web.Models.Processor

<h2>ProcessorsEdit</h2>

@using (Html.BeginForm("Edit", "Processors"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(x => x.CompanyName)</div>
    <div class="editor-field">@Html.EditorFor(x => x.CompanyName)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Name)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Name)</div>

    <div class="editor-label">@Html.LabelFor(x => x.CoreCount)</div>
    <div class="editor-field">@Html.EditorFor(x => x.CoreCount)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Ghz)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Ghz)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Price)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Price)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Socket)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Socket)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Damaged)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Damaged)</div>

    <input type="submit" value="SEND" />

}

oenik_prog3_2020_2_rcn5hx/Computers.Web/Views/Processors/ProcessorsIndex.cshtml
@model Computers.Web.Models.ProcessorListViewModel

@{ 
    ViewData["Title"] = "ProcessorsIndex";
}

<h2>Processors Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("ProcessorsEdit", Model.EditedProcessor)

@await Html.PartialAsync("ProcessorsList", Model.ListOfProcessor)

oenik_prog3_2020_2_rcn5hx/Computers.Web/Views/Processors/ProcessorsList.cshtml
@model IEnumerable<Computers.Web.Models.Processor>

<h2>ProcessorsList</h2>

@if (Model.Count() == 0)
{ 
    <p>No data in the database!</p>
}
else
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(x => x.First().CompanyName)</th>
        <th>@Html.DisplayNameFor(x => x.First().Name)</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Modify</th>
    </tr>
    @foreach (var proc in Model)
    {
        <tr>
            <td>@Html.DisplayFor(x => proc.CompanyName)</td>
            <td>@Html.DisplayFor(x => proc.Name)</td>
            <td>@Html.ActionLink("[SHOW]", "Details", new { id = proc.Id})</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { id = proc.Id})</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { id = proc.Id})</td>
        </tr>
    }
</table>
}